---
version: v1alpha1
debug: false

# Logging settings
logging:
  # Output format to use: [text|json]
  format: text
  # If set to true, the log events will contain the source code position of the
  # log statements.
  add_source: false
  # Log level: [info|warn|error|debug]
  level: info

  # An optional key/value map of attributes to add to each log event
  # attributes:
  #   landscape: dev

# Redis settings
redis:
  endpoint: redis:6379

# Database settings
database:
  dsn: "postgresql://inventory:p4ssw0rd@postgres:5432/inventory?sslmode=disable"

# Worker settings
worker:
  # Concurrency level
  concurrency: 100

  # Priority queue configuration.
  #
  # Check the following documentation for more details about how priority queues
  # work.
  # See https://github.com/hibiken/asynq/wiki/Queue-Priority
  queues:
    odg: 1

  # Strict priority specifies whether queue priority is treated strictly.
  #
  # When set to true tasks from queues with higher priority are always processed
  # first, and tasks from queues with lower priority are processed only after
  # higher priority queues are empty.
  strict_priority: false
